//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.04 at 05:10:14 PM CET 
//


package hap.ruleengine.parts.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WireDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WireDef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="sourceComponent" type="{}UUID" />
 *       &lt;attribute name="sourceOutput" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="targetComponent" type="{}UUID" />
 *       &lt;attribute name="targetInput" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="BooleanWire|StringWire|DoubleWire"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WireDef")
public class WireDef {

    @XmlAttribute(name = "sourceComponent")
    protected String sourceComponent;
    @XmlAttribute(name = "sourceOutput")
    protected String sourceOutput;
    @XmlAttribute(name = "targetComponent")
    protected String targetComponent;
    @XmlAttribute(name = "targetInput")
    protected String targetInput;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the sourceComponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceComponent() {
        return sourceComponent;
    }

    /**
     * Sets the value of the sourceComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceComponent(String value) {
        this.sourceComponent = value;
    }

    /**
     * Gets the value of the sourceOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOutput() {
        return sourceOutput;
    }

    /**
     * Sets the value of the sourceOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOutput(String value) {
        this.sourceOutput = value;
    }

    /**
     * Gets the value of the targetComponent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetComponent() {
        return targetComponent;
    }

    /**
     * Sets the value of the targetComponent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetComponent(String value) {
        this.targetComponent = value;
    }

    /**
     * Gets the value of the targetInput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetInput() {
        return targetInput;
    }

    /**
     * Sets the value of the targetInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetInput(String value) {
        this.targetInput = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
